<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/css" href="lab12.css"?>
<!DOCTYPE EXAM [
<!ELEMENT EXAM (EXAMNAME, SUBJECT)>
<!ELEMENT EXAMNAME (#PCDATA)>
<!ELEMENT SUBJECT (NAME, DATE, TIME)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT DATE (#PCDATA)>
<!ELEMENT TIME (#PCDATA)>
<!ENTITY time "Время: ">
]>
<EXAM>
    <EXAMNAME>Предмет</EXAMNAME>
    <SUBJECT>
        <NAME>Физика</NAME>
        <DATE>06.01.2022</DATE>
        <TIME>&time;13:00</TIME>
    </SUBJECT>
    <SUBJECT>
        <NAME>Линейная алгебра и аналитическая геометрия</NAME>
        <DATE>11.01.2022</DATE>
        <TIME>&time;13:00</TIME>
    </SUBJECT>
    <SUBJECT>
        <NAME>Математическиий анализ</NAME>
        <DATE>15.01.2022</DATE>
        <TIME>&time;13:00</TIME>
    </SUBJECT>
    <SUBJECT>
        <NAME>Арифметическо-логические основы ВС</NAME>
        <DATE>19.01.2022</DATE>
        <TIME>&time;13:00</TIME>
    </SUBJECT>
    <SUBJECT>
        <NAME>Основы алгоритмизации и програмирования</NAME>
        <DATE>23.01.2022</DATE>
        <TIME>&time;13:00</TIME>
    </SUBJECT>
</EXAM>